server:
  contextPath: /maintenance
  
docker.url: tcp://10.0.0.6:2375
domain.url: http://ribbitupcoreos.southeastasia.cloudapp.azure.com

file.dir: /dockerClientTest
file.name: userApp.data
apache.conf.name: out.conf

maintenance.container.name: nostalgic_poitras
apache.container.name: apache2
apache.container.conf.path: /etc/apache2/sites-available
apache.container.default.conf.name: 000-default.conf