server:
  contextPath: /maintenance
  
docker.url: tcp://10.0.0.6:2375
domain.url: http://ribbitupcoreos.southeastasia.cloudapp.azure.com

file.dir: /dockerClientTest
file.name: userApp.data
apache.conf.name: out.conf

maintenance.container.name: management
apache.container.name: apache2
apache.container.conf.path: /etc/apache2/sites-available
apache.container.default.conf.name: 000-default.conf

ribbitup.container.ext.name: ribbitup
ribbitup.container.url: http://ribbitup:9001

management.container.ext.name: maint
management.container.url: http://management:8080/mainenance