server:
  contextPath: /maintenance
  
docker.url: http://10.0.0.6:2375
domain.url: http://ribbitupcoreos.southeastasia.cloudapp.azure.com

file.dir: /dockerClientTest
file.name: userApp.data
apache.conf.name: out.conf